### ISSUE TITLE
Is that possible to run it on linux?

### ISSUE THREAD

**Issue by lemchen** [lvzixun/clang-complete#1]
Could you supply a linux version?

**Comment by lvzixun** [comment]
I add ubuntu support.
if ubuntu platform, command is as follows:

```
$ git clone https://github.com/lvzixun/clang-complete.git
$ make linux
$ make install
```

if other linux:
you have to download that  `libclang.so` from [llvm.org](http://llvm.org/releases/download.html).
you can also download the source code to be compiled. ;)

**Comment by lemchen** [comment]
That's great.
