### ISSUE TITLE
Does not work with STL

### ISSUE THREAD

**Issue by krvajal** [lvzixun/clang-complete#2]
I just downloaded it and try to get autocompletion when using the stl classes like vector and list and it does not find those files

**Comment by lvzixun** [comment]
add include headfile  `"-isystem", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",` at cc.sublime-settings. ;)

**Comment by krvajal** [comment]
Nice.
