### ISSUE TITLE
可以加些sublimeclang里不显示warning的设置么

### ISSUE THREAD

**Issue by yzh89** [lvzixun/clang-complete#24]
之前试过sublimeclang (https://github.com/quarnster/SublimeClang) 那个在windows上有些问题， linux下OK, 但是有时读大的库有些慢，这个包会有区别么? SublimeClang option 有个ignore某些warning的设置很好用。希望能够加上那个选项。

**Comment by lvzixun** [comment]
前段时间有人提交了一个pr  #19 ， 应该是已经merge过来了。
实现了对error的ignore. 但是对具体的warning进行设置貌似还不支持。

PS： 最近工作上的事情太多，这个插件已经好久没玩了。-_-!

**Comment by riteme** [comment]
你可以在include_options里面加入-Wno-XXX就可以屏蔽特定的warning了，并不是很麻烦吧

**Comment by lvzixun** [comment]
你可以试试在`cc.sublime-settings`文件中`include_options`section 中添加上对应的`-Wno-XXX`。初始化`clang`的时候应该会将这个参数传进去的

**Comment by yzh89** [comment]
谢啦
