### ISSUE TITLE
c++语法检测不对，use of undeclared identifier 'cout'

### ISSUE THREAD

**Issue by ladevan** [lvzixun/clang-complete#30]
你好，

谢谢你开发这个插件。我在使用这个插件时发现好像语法检测有些问题，我用了"using namespace std"后，使用cout，语法检测会提示“use of undeclared identifier 'cout'。

源文件开头已经包含"iostream", 环境为Mac OS X Yosemite

以下是Log输出
reloading plugin Vintageous.test_runner
reloading plugin Vintageous.xactions
reloading plugin Vintageous.xmotions
reloading plugin Vintageous.xsupport
reloading plugin Vintageous.xsupport_mouse
reloading plugin Clang-Complete.cc
reloading plugin Clang-Complete.clang
reloading plugin Clang-Complete.clang_error
reloading plugin Clang-Complete.enum
reloading plugin Clang-Complete.st_cc
reloading plugin LaTeXTools.delete_temp_files
reloading plugin LaTeXTools.getTeXRoot
reloading plugin LaTeXTools.jumpToPDF
reloading plugin LaTeXTools.kpsewhich
reloading plugin LaTeXTools.latex_cite_completions
reloading plugin LaTeXTools.latex_ref_cite_completions
reloading plugin LaTeXTools.latex_ref_completions
reloading plugin LaTeXTools.latexCommand
reloading plugin LaTeXTools.latexEnvCloser
reloading plugin LaTeXTools.latexEnvironment
reloading plugin LaTeXTools.makePDF
reloading plugin LaTeXTools.migrate
reloading plugin LaTeXTools.parseTeXlog
reloading plugin LaTeXTools.texMacro
reloading plugin LaTeXTools.texSections
reloading plugin LaTeXTools.toggle_auto
reloading plugin LaTeXTools.toggle_focus
reloading plugin LaTeXTools.toggle_fwdsync
reloading plugin LaTeXTools.toggle_show
reloading plugin LaTeXTools.viewPDF
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeREPL.**init**
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
plugins loaded
SublimeLinter: debug mode: off 
SublimeLinter: WARNING: import of pyflakes.api module in pyflakes failed, linter will not work with python 3 code 
clang options:  ['-xc++', '-I/Users/dengyuliu/Downloads/VIO/include/', '-I/usr/local/Cellar/eigen/3.2.4/include/eigen3/']

谢谢！

**Comment by lvzixun** [comment]
确认你是否`#include<iostream>`， 同时确认下c++的头文件路径是否正确，配置在`cc.sublime-settings`文件中的`include_options`。 默认配置为`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1`

**Comment by ladevan** [comment]
谢谢回复！我在我的project setting里面添加以上路径就可以了。我看见在`cc.sublime-settings`里已经添加了以上路径，但因为我在自己项目的`setting`里添加了其它路径而没有添加C++头文件路径，似乎就不行了。所以，我必须在我的每个项目配置里都添加这些路径（如果我有其它项目相关的头文件路径的话）？

**Comment by lvzixun** [comment]
在`cc.sublime-settings`中添加是全局生效的，`project setting`的配置只是会对当前`project`生效。一般是添加完`include_options`之后是需要重启才能生效， 你重启下`sublime`试试。如果还不行的话，查看下控制台看看有没有抛出异常 ;)

**Comment by ladevan** [comment]
谢谢！但我看你的`cc.sublime-settings`中有说如果存在`project setting`的配置的话，默认配置就会被覆盖。这意味着假如我的项目中需要用C++基本头文件，同时也需要包含其他头文件，我每次都需要在项目配置中添加MacOS的C++基本头文件？

**Comment by lvzixun** [comment]
从`cc_st.py`代码上面看

``` .py
 def get_opt(view):
    settings = Complete.get_settings()
    additional_lang_opts = settings.get("additional_language_options", {})
    language = get_language(view)
    include_opts = settings.get("include_options", [])
    project_data = sublime.active_window().project_data()
    if "cc_include_options" in project_data:
      include_opts = include_opts + project_data["cc_include_options"]
```

是会做merge的。 你是从package controller 上面下的还是直接从github这边clone安装的？

**Comment by ladevan** [comment]
我这里的`st_cc.py`代码是这样的：

``` python
@staticmethod
  def get_opt(view):
    settings = Complete.get_settings()
    additional_lang_opts = settings.get("additional_language_options", {})
    language = get_language(view)
    s = view.settings()
    include_opts = s.has("cc_include_options") and s.get("cc_include_options", []) or settings.get("include_options", [])

    window = sublime.active_window()
    variables = window.extract_variables()
    include_opts = sublime.expand_variables(include_opts, variables)

    opt = [drivers[language]]
    if language in additional_lang_opts:
      for v in additional_lang_opts[language]:
        opt.append(v)

    for v in include_opts:
      opt.append(v)
    print("clang options: ", opt)
    return opt
```

看来是Package Control上没有更新？

**Comment by lvzixun** [comment]
由于之前有位朋友提交了支持window的PR，里面包含了很大的dll。我不小心merge到`master`上面了，所以就没发布release。刚才我新建了`window`分支，把dll从master上面去掉了，同时发布了新版本的release，你待会儿应该就能从`package control`上面下载到了

PS: 新的release版本为, `0.1.12`

**Comment by ladevan** [comment]
好的，多谢！:-)
