### ISSUE TITLE
Project settings are no longer read correctly

### ISSUE THREAD

**Issue by fpottbaecker** [lvzixun/clang-complete#31]
The project specific `cc_include_options` settings are no longer read correctly, a project that used to be configured properly does not work anymore since a few days.

It seems that since 092145e07d4aa4ad14abf85a27fb8de37ca25f40 the project data is accessed directly and the include options are taken from the root `project_data`, although they should be taken from `project_data["settings"]`. [A quick edit fixed this problem](https://github.com/lvzixun/Clang-Complete/blob/master/st_cc.py#L162-L163):

``` python
    if project_data and "settings" in project_data and "cc_include_options" in project_data["settings"]:
      include_opts = include_opts + project_data["settings"]["cc_include_options"]
```

Could it be, that the readme is outdated(the include options should now be in the root project data and the project specific options now _add_ to the root settings instead of _overwriting_ them)?
Also is there any reason to stop using `view.settings()`?

**Comment by lvzixun** [comment]
I forget change `README.md` when merge 092145e pr.  I fix get `cc_include_options` subsection from `project settings`.
