### ISSUE TITLE
Sublime hangs on completion

### ISSUE THREAD

**Issue by Jo2003** [lvzixun/clang-complete#33]
#### short description

When making code changes in included files (added through cc_include_options) sublime text will hang next time the autocomplete popup should bring up new values from last edit. After some time the plugin-host will crash. 

I'm running your great plugin on Linux (Ubuntu 14.04 x64). This happens in a large project (50+ files) with a huge count of namespaces.
#### a more complete description

Assuming we have a project and in an included folder (through cc_include_options) we have the file _include.h_ with following content:

``` C++
...
enum class foo : uint16_t {
   NOTHING,
   SOME,
   MORE,
   ALL
};
...
```

In a cpp file (e.g. test.cpp) this file is included. Now I add some elements to the defined enum (e.g. NO_INFO) and save this file. Next in test.cpp file I type:

``` C++
foo bar;
bar = foo::...;
```

Now, when the autocomplete popup should list all possible values the popup appears and sublime hangs. 

Could you please have a look?

Thanks in advance,
   Jörg

**Comment by riteme** [comment]
Completion is incomplete. There's something wrong in the completeions of overloads functions, inherited functions, template arguments and enums.

似乎函数重载，继承函数，模板类型和枚举的补全有比较大的问题。感觉C++几乎没法用...

希望改进一下;)
