### ISSUE TITLE
Including custom header files does not work (reopening issue #3)

### ISSUE THREAD

**Issue by SolarSunrise** [lvzixun/clang-complete#5]
I'm aware of my previous issue (#3) has been closed, but I would like you to know that it is still not possible, at least for me, to include custom header files in the (project_name).sublime-project file. However, I can include my project files in the cc.sublime-settings:
   "include_options":
   [
        "-isystem", "/Users/.../include2,
        "-isystem", "/Users/.../include1",
   ]

Thank you for your contribution in this plugin! I am looking forward for this fix.

**Comment by lvzixun** [comment]
verify your `<project_name>.sublime-project` file is correct. and `cc_include_options` section is valid.
my `test.sublime-project` file as follow:

```
{
    "folders":
    [
        {
            "path": "."
        }
    ],

  "settings":
  {
    "cc_include_options":
    [
      "-I/Users/zixunlv/codes/A2/src/"
    ]
  }
}
```

PS:  if you modify `<project_name>.sublime-project` file, must restart sublime Text to take effect. ;D

**Comment by SolarSunrise** [comment]
It turned out I was using a project file from Sublime Text 2, thus it wasn't compatible with Sublime Text 3. I created a new project and now it is working fine!
Thanks for your work! Now I can finally move to Sublime Text 3 thanks to your plugin... (I was using Sublime Text 2 with SublimeClang, which is discontinued)

The issue can be closed =)

**Comment by lvzixun** [comment]
I recommend that update 0.1.6 version,  you can also update from package control. 
is my pleasure to help you. ;)
