### ISSUE TITLE
Change formatting for keyword completion.

### ISSUE THREAD

**Issue by drammelt** [lvzixun/clang-complete#7]
Clang-Complete appears to override Snippets for the same keywords so it would be nice if there were some way to format the completion for keywords and such.

Using the if statement completion I from Clang-Complete I get...

```
if(expression){statements
}
```

Which is pretty horrible. What I want is what the C++ Starting Kit snippets provide such as this...

```
if (/* condition */)
{
    /* code */
}
```

So is there anyway to override the Clang-Complete completion with Snippets from elsewhere or is there some way to format the output from Clang-Complete?

**Comment by lvzixun** [comment]
I update new version `0.1.8`. 
you can set `inhibit` section to whether or not to inhibit the ST3 built in word completions at `cc.sublime-settings` file.

**Comment by drammelt** [comment]
Perfect thank you.
