### ISSUE TITLE
Cannot find the file error

### ISSUE THREAD

**Issue by sittim** [lvzixun/clang-complete#8]
Hi,

I keep getting this error:

```
/work/c1202-firmware/msp430-os/dispatcher.h:11:10: fatal error: 'msp430-os/array_safe.h' file not found
```

and it points to line of code

``` c++
#include "msp430-os/array_safe.h"
```

I do have a file named `cc.sublime-settings` with listing:

``` js
{
    "include_options":
    [
        "-I/work/c1202-firmware/"
    ]
}
```

If I ran command `subl /work/c1202-firmware/msp430-os/array_safe.h`, the file opens, so it does exist.  So why is clang complaining that the file does not exist?

**Comment by sittim** [comment]
I found that placing the `cc_include_options` in sublime project file works well, but, for the changes to take effect, sublime requires restart.  But I just cannot get the `cc.sublime-settings`  `include_options` to work.  Even when the `cc_include_options` are not in the sublime project file.

**Comment by lvzixun** [comment]
the error:

```
/work/c1202-firmware/msp430-os/dispatcher.h:11:10: fatal error: 'msp430-os/array_safe.h' file not found
```

`#include "array_safe.h"` instead of `#include "msp430-os/array_safe.h"`

if `"cc_include_options"` exists in your project settings, it'll override rather than add to the `"include_options"` defined in `cc.sublime-settings`

**Comment by sittim** [comment]
Lvzixun,

the google coding style guide for C++, requires the subdirectory, any way to make  `#include "msp430-os/array_safe.h"`, work?

**Comment by lvzixun** [comment]
if you add `"-I/work/c1202-firmware/"` at  `include_options` section of  `cc.sublime-settings` file.
`#include "sp430-os/array_safe.h"` able to work normally.

check your modified `cc.sublime-settings` file is `/Users/guys/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/cc.sublime-settings`. ;)

**Comment by sittim** [comment]
I did not touch the file `~/.config/sublime-text-3/Packages/Clang-Complete/cc.sublime-settings`, since it is part of the repo to keep it upgradeable.  So per the `README.md` file, I made a custom `cc.sublime-settings` in the Packages directory, i.e.  `~/.config/sublime-text-3/Packages/cc.sublime-settings`.  Does the `cc.sublime-settings` in `Clang-Complete` directory need be deleted?

**Comment by lvzixun** [comment]
clang-complete plugin only read `~/.config/sublime-text-3/Packages/Clang-Complete/cc.sublime-settings`.   so, remove your custom file `~/.config/sublime-text-3/Packages/cc.sublime-settings`.

I could not clearly described in `README.md`.

**Comment by sittim** [comment]
OK that works, thanks...
